spring:
  application:
    name: Book

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: abc
    password: password
    initialization-mode: always
    data: classpath:/testdb/data.sql
    schema: classpath:/schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

spring-doc:
  swagger-ui:
    path: /swagger


#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true
#  swagger-ui-path: /swagger
server:
  port: 8080
  servlet:
    context-path: /
